### ISSUE TITLE
Kalm-Wordpress: Not working with Calm 2.9.0 + AOS 5.11 + Karbon 1.0.3

### ISSUE THREAD

**Issue by rafabolivar** [nutanix/blueprints#13]
Hi guys,

I have tried to import the Kalm-Wordpress blueprint using Calm 2.9.0 + AOS 5.11 + Karbon 1.0.3 and it's unable to import, returning the message "looks like something went wrong here". Is there any workaround to fix it?

![image](https://user-images.githubusercontent.com/37837380/68377234-4b414d80-014a-11ea-9b71-bea1ed098cee.png)

**Comment by charanteja333** [comment]
@rafabolivar  We uploaded the same BP on 2.9.8 and it worked fine for us.

**Comment by aadis** [comment]
Can we close this issue?

**Comment by rafabolivar** [comment]
Yes, please.
